//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalUsers) DeepCopyInto(out *AdditionalUsers) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalUsers.
func (in *AdditionalUsers) DeepCopy() *AdditionalUsers {
	if in == nil {
		return nil
	}
	out := new(AdditionalUsers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConnectionReference) DeepCopyInto(out *DatabaseConnectionReference) {
	*out = *in
	out.DatabaseObjectReference = in.DatabaseObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConnectionReference.
func (in *DatabaseConnectionReference) DeepCopy() *DatabaseConnectionReference {
	if in == nil {
		return nil
	}
	out := new(DatabaseConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMongoDBProvider) DeepCopyInto(out *DatabaseMongoDBProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMongoDBProvider.
func (in *DatabaseMongoDBProvider) DeepCopy() *DatabaseMongoDBProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseMongoDBProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseMongoDBProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMongoDBProviderList) DeepCopyInto(out *DatabaseMongoDBProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseMongoDBProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMongoDBProviderList.
func (in *DatabaseMongoDBProviderList) DeepCopy() *DatabaseMongoDBProviderList {
	if in == nil {
		return nil
	}
	out := new(DatabaseMongoDBProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseMongoDBProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMongoDBProviderSpec) DeepCopyInto(out *DatabaseMongoDBProviderSpec) {
	*out = *in
	if in.MongoDBConnections != nil {
		in, out := &in.MongoDBConnections, &out.MongoDBConnections
		*out = make([]MongoDBConnection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMongoDBProviderSpec.
func (in *DatabaseMongoDBProviderSpec) DeepCopy() *DatabaseMongoDBProviderSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseMongoDBProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMongoDBProviderStatus) DeepCopyInto(out *DatabaseMongoDBProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMongoDBProviderStatus.
func (in *DatabaseMongoDBProviderStatus) DeepCopy() *DatabaseMongoDBProviderStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseMongoDBProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMySQLProvider) DeepCopyInto(out *DatabaseMySQLProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMySQLProvider.
func (in *DatabaseMySQLProvider) DeepCopy() *DatabaseMySQLProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseMySQLProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseMySQLProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMySQLProviderList) DeepCopyInto(out *DatabaseMySQLProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseMySQLProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMySQLProviderList.
func (in *DatabaseMySQLProviderList) DeepCopy() *DatabaseMySQLProviderList {
	if in == nil {
		return nil
	}
	out := new(DatabaseMySQLProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseMySQLProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMySQLProviderSpec) DeepCopyInto(out *DatabaseMySQLProviderSpec) {
	*out = *in
	if in.MySQLConnections != nil {
		in, out := &in.MySQLConnections, &out.MySQLConnections
		*out = make([]MySQLConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMySQLProviderSpec.
func (in *DatabaseMySQLProviderSpec) DeepCopy() *DatabaseMySQLProviderSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseMySQLProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMySQLProviderStatus) DeepCopyInto(out *DatabaseMySQLProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MySQLConnectionVersions != nil {
		in, out := &in.MySQLConnectionVersions, &out.MySQLConnectionVersions
		*out = make([]MySQLConnectionVersion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMySQLProviderStatus.
func (in *DatabaseMySQLProviderStatus) DeepCopy() *DatabaseMySQLProviderStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseMySQLProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePostgreSQLProvider) DeepCopyInto(out *DatabasePostgreSQLProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePostgreSQLProvider.
func (in *DatabasePostgreSQLProvider) DeepCopy() *DatabasePostgreSQLProvider {
	if in == nil {
		return nil
	}
	out := new(DatabasePostgreSQLProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabasePostgreSQLProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePostgreSQLProviderList) DeepCopyInto(out *DatabasePostgreSQLProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabasePostgreSQLProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePostgreSQLProviderList.
func (in *DatabasePostgreSQLProviderList) DeepCopy() *DatabasePostgreSQLProviderList {
	if in == nil {
		return nil
	}
	out := new(DatabasePostgreSQLProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabasePostgreSQLProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePostgreSQLProviderSpec) DeepCopyInto(out *DatabasePostgreSQLProviderSpec) {
	*out = *in
	if in.PostgreSQLConnections != nil {
		in, out := &in.PostgreSQLConnections, &out.PostgreSQLConnections
		*out = make([]PostgreSQLConnection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePostgreSQLProviderSpec.
func (in *DatabasePostgreSQLProviderSpec) DeepCopy() *DatabasePostgreSQLProviderSpec {
	if in == nil {
		return nil
	}
	out := new(DatabasePostgreSQLProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePostgreSQLProviderStatus) DeepCopyInto(out *DatabasePostgreSQLProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePostgreSQLProviderStatus.
func (in *DatabasePostgreSQLProviderStatus) DeepCopy() *DatabasePostgreSQLProviderStatus {
	if in == nil {
		return nil
	}
	out := new(DatabasePostgreSQLProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequest) DeepCopyInto(out *DatabaseRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequest.
func (in *DatabaseRequest) DeepCopy() *DatabaseRequest {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequestList) DeepCopyInto(out *DatabaseRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequestList.
func (in *DatabaseRequestList) DeepCopy() *DatabaseRequestList {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequestSpec) DeepCopyInto(out *DatabaseRequestSpec) {
	*out = *in
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.AdditionalUsers != nil {
		in, out := &in.AdditionalUsers, &out.AdditionalUsers
		*out = new(AdditionalUsers)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseConnectionReference != nil {
		in, out := &in.DatabaseConnectionReference, &out.DatabaseConnectionReference
		*out = new(DatabaseConnectionReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequestSpec.
func (in *DatabaseRequestSpec) DeepCopy() *DatabaseRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequestStatus) DeepCopyInto(out *DatabaseRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequestStatus.
func (in *DatabaseRequestStatus) DeepCopy() *DatabaseRequestStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBConnection) DeepCopyInto(out *MongoDBConnection) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBConnection.
func (in *MongoDBConnection) DeepCopy() *MongoDBConnection {
	if in == nil {
		return nil
	}
	out := new(MongoDBConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLConnection) DeepCopyInto(out *MySQLConnection) {
	*out = *in
	if in.ReplicaHostnames != nil {
		in, out := &in.ReplicaHostnames, &out.ReplicaHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLConnection.
func (in *MySQLConnection) DeepCopy() *MySQLConnection {
	if in == nil {
		return nil
	}
	out := new(MySQLConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLConnectionVersion) DeepCopyInto(out *MySQLConnectionVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLConnectionVersion.
func (in *MySQLConnectionVersion) DeepCopy() *MySQLConnectionVersion {
	if in == nil {
		return nil
	}
	out := new(MySQLConnectionVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConnection) DeepCopyInto(out *PostgreSQLConnection) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConnection.
func (in *PostgreSQLConnection) DeepCopy() *PostgreSQLConnection {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConnection)
	in.DeepCopyInto(out)
	return out
}
